apiVersion: apps/v1
kind: Deployment
metadata:
  name: world-capital-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: world-capital-app
  template:
    metadata:
      labels:
        app: world-capital-app
    spec:
      containers:
      - name: world-capital-app
        image: yourdockerhubusername/worldcapitalquiz
        ports:
        - containerPort: 3000
        env:
        - name: DB_HOST
          value: postgres-service
        - name: DB_USER
          value: postgres
        - name: DB_PASS
          value: password123
        - name: DB_NAME
          value: world
---
